export const GOVERNANCE_CLIENT_ERRORS = new Set([
  "UNAUTHENTICATED", "WORKBENCH_READ_ONLY", "INVALID_CLOCK", "VERSION_CONFLICT", "DUPLICATE_CONFLICT",
  "GOVERNANCE_PERMISSION_DENIED", "GOVERNANCE_VERSION_CHANGED", "GOVERNANCE_VERSION_HASH_MISMATCH", "GOVERNANCE_VERSION_OUT_OF_SCOPE",
  "GATE_CHECKS_INCOMPLETE", "GATE_EVIDENCE_EXPIRED", "GATE_EVIDENCE_OUT_OF_SCOPE", "INVALID_GATE_EVIDENCE", "NO_ACTIVE_GOVERNANCE", "POLICY_REVIEW_OVERDUE",
  "STRATEGY_ADMISSION_THRESHOLDS_FAILED", "STRATEGY_EVIDENCE_METRICS_MISMATCH", "STRATEGY_EVIDENCE_NOT_READY", "STRATEGY_POLICY_MISMATCH",
  "ACCOUNT_CAPABILITY_MISSING", "ACCOUNT_NOT_AUTHORIZED", "ACCOUNT_RECONCILIATION_REQUIRED", "ACCOUNT_SCOPE_INCOMPLETE", "ACCOUNT_OUT_OF_SCOPE",
  "ACTUAL_DATA_NOT_VERIFIED", "AI_REVIEW_REQUIRED", "CURRENT_COMPLETE_VALUATION_REQUIRED", "EXECUTION_LIQUIDITY_BLOCKED", "EXPOSURE_UNVERIFIED", "FEE_BUDGET_INVALID",
  "FUTURE_MARKET_PUBLICATION", "INSUFFICIENT_AVAILABLE_CASH", "INSUFFICIENT_AVAILABLE_SHARES", "INVALID_CASH_HOLD", "INVALID_FX_RATE", "INVALID_LEDGER_LIABILITY",
  "INVALID_LISTING_CURRENCY", "INVALID_PROPOSAL_AMOUNTS", "INVALID_TRADING_INCREMENT", "LISTING_NOT_AUTHORIZED", "LISTING_NOT_TRADABLE", "LISTING_NOT_FOUND",
  "LISTING_REVIEW_MISSING", "LISTING_REVIEW_EXPIRED", "LISTING_REVIEW_NOT_ETF", "LISTING_REVIEW_NOT_ACTIVE", "LISTING_REVIEW_TRADING_UNITS_MISSING", "LISTING_REVIEW_RISK_CLASSIFICATION_MISSING",
  "LISTING_REVIEW_EVIDENCE_INVALID", "LISTING_REVIEW_OUT_OF_SCOPE", "LISTING_REVIEW_IDENTITY_CHANGED", "LISTING_REVIEW_CHANGED",
  "LISTING_REVIEW_PRODUCT_NOT_SUPPORTED", "LISTING_REVIEW_PRODUCT_STRUCTURE_UNKNOWN",
  "MARKET_PRICE_BASIS_INVALID", "MARKET_PUBLICATION_MISSING", "MARKET_UNITS_INVALID", "MARKET_OBSERVATION_TIME_INVALID", "MARKET_OBSERVATION_AMBIGUOUS", "PRICE_CALENDAR_UNVERIFIED", "PRICE_CALENDAR_EVIDENCE_INVALID", "MINIMUM_CASH_BREACHED", "NEGATIVE_TARGET_POSITION", "NONPOSITIVE_POST_TRADE_NAV",
  "ORDER_BUDGET_EXCEEDED", "POSITION_INPUT_INCOMPLETE", "PRICE_DEVIATION_EXCEEDED", "PROPOSAL_EXPIRED", "PROPOSAL_LEDGER_CHANGED", "PROPOSAL_MARKET_CHANGED",
  "PROPOSAL_NOT_NETTED", "PROPOSAL_OUT_OF_SCOPE", "STRATEGY_BUDGET_EXCEEDED", "STRATEGY_UNIVERSE_MISMATCH", "VALUATION_ITEMS_REQUIRED", "VALUATION_MARKET_CHANGED",
  "VALUATION_NOT_CURRENT", "VALUATION_STALE", "ACTIVATION_TIMESTAMP_CONFLICT", "APPROVAL_STALE", "CAPABILITY_ALREADY_ACTIVE", "CAPABILITY_EXPIRED",
  "EXECUTION_FACT_ALREADY_LINKED", "EXECUTION_FACT_OUT_OF_SCOPE", "EXECUTION_REPORT_DUPLICATE_CONFLICT", "INVALID_CAPABILITY_SCOPE", "INVALID_PROPOSAL_EXPIRY", "PROPOSAL_ALREADY_APPROVED",
  "PROPOSAL_ITEM_OUT_OF_SCOPE", "PROPOSAL_NOT_EXPIRED", "PROPOSAL_TERMINAL", "RESERVATION_NOT_ACTIVE", "RISK_APPROVAL_MISMATCH", "RISK_INPUT_CHANGED", "RISK_INPUT_INVALID",
  "FORMAL_STRATEGY_EVIDENCE_REQUIRED", "INVALID_VERIFICATION_MANIFEST", "RUNTIME_RELEASE_MANIFEST_REQUIRED", "TRUSTED_VERIFICATION_INCOMPLETE",
  "TRUSTED_VERIFICATION_JOB_REQUIRED", "TRUSTED_VERIFICATION_REQUIRED", "VERIFICATION_MANIFEST_MISMATCH", "VERIFICATION_NOT_ACTUAL_PASS",
  "VERIFICATION_SOURCE_MANIFEST_INCOMPLETE", "VERIFICATION_TIME_INVALID", "VERIFICATION_VERSION_MISMATCH",
  "ATTACHMENT_DATA_DIR_REQUIRED", "ATTACHMENT_HASH_MISMATCH", "ATTACHMENT_NOT_FOUND", "ATTACHMENT_OUT_OF_SCOPE", "ATTACHMENT_SIZE_MISMATCH", "ATTACHMENT_TOO_LARGE",
  "INVALID_ATTACHMENT_METADATA", "INVALID_ATTACHMENT_TEXT", "INVALID_ATTACHMENT_UTF8", "UNSAFE_ATTACHMENT_DIRECTORY", "UNSAFE_ATTACHMENT_PERMISSIONS",
]);

export function isGovernanceClientError(message: string): boolean {
  if (GOVERNANCE_CLIENT_ERRORS.has(message)) return true;
  if (/^CONCENTRATION_LIMIT_EXCEEDED:(listing|index|market|currency|region|sector)$/.test(message)) return true;
  if (/^MARKET_OBSERVATION_UNAVAILABLE:(close|spread_bps|premium_bps|turnover|volume|fx_cny_per_unit)$/.test(message)) return true;
  return message.startsWith("RISK_BLOCKED:") && !message.slice(13).startsWith("RISK_BLOCKED:") && isGovernanceClientError(message.slice(13));
}
