import { z } from "zod";
import { listingIdentitySchema, listingReviewFactsSchema, publishListingReviewSchema, reviewHash, reviewId, reviewInstant, type PublishListingReviewCommand } from "@/server/listing-reviews/schemas";
import type { ListingReviewDocument, ListingReviewState } from "@/server/listing-reviews/types";
export type ListingReviewDraft = { sourceId: string; sourceHash: string; instrumentKind: string; lifecycleStatus: string; leverage: string; direction: string; quantityStep: string; priceStep: string; effectiveDate: string; fundId: string; shareClassId: string; indexId: string; region: string; sector: string; reviewUntil: string; reason: string };
export const emptyListingReviewDraft = (): ListingReviewDraft => ({ sourceId: "", sourceHash: "", instrumentKind: "", lifecycleStatus: "", leverage: "", direction: "", quantityStep: "", priceStep: "", effectiveDate: "", fundId: "", shareClassId: "", indexId: "", region: "", sector: "", reviewUntil: "", reason: "" });
export type ListingReviewPending = { portfolio: string; listing: string; binding: string; body: string; command: PublishListingReviewCommand; identity: ListingReviewState["rows"][number]["identity"]; sourceKnownAt: string | null };
const text = (max: number) => z.string().min(1).max(max);
const natural = z.number().int().min(0).max(Number.MAX_SAFE_INTEGER);
const quality = z.enum(["complete", "blocked"]), issues = z.array(z.string().regex(/^LISTING_REVIEW_[A-Z_]+$/)).max(20);
const documentSchema = z.object({ schema_version: z.literal("listing-review-v1"), id: reviewId, portfolio_id: reviewId, listing_id: reviewId, revision: natural.refine(n => n > 0), source_id: reviewId, source_hash: reviewHash, source_known_at: reviewInstant, identity_snapshot: listingIdentitySchema, identity_hash: reviewHash, known_at: reviewInstant, created_by: reviewId.refine(id => !id.startsWith("system:")), review_until: reviewInstant, reason: text(2000), review_basis: z.literal("human_reviewed_not_provider_verified"), facts: listingReviewFactsSchema }).strict();
const review = z.object({ document: documentSchema, content_hash: reviewHash, audit_id: reviewId, proof_hash: reviewHash, quality, issues }).strict();
const row = z.object({ identity: listingIdentitySchema, identity_hash: reviewHash, name: text(1000), review_revision: natural, quality, issues, current: review.nullable() }).strict();
const stateSchema = z.object({ schema_version: z.literal("listing-review-state-v1"), session_binding: reviewHash, portfolios: z.array(z.object({ id: reviewId, name: text(1000) }).strict()).max(1000), portfolios_truncated: z.boolean(), selected_portfolio_id: reviewId.nullable(), selected_listing_id: reviewId.nullable(), catalog_revision: natural, read_only: z.boolean(), checked_at: reviewInstant, resource_hash: reviewHash, rows: z.array(row).max(50), next_cursor: text(1024).nullable(), selected: row.nullable(), sources: z.array(z.object({ id: reviewId, portfolio_id: reviewId, reference: text(2000), content_hash: reviewHash, known_at: reviewInstant, created_by: reviewId }).strict()).max(100), sources_truncated: z.boolean(), history: z.array(review).max(20), history_truncated: z.boolean() }).strict();
export function assertListingReviewState(value: unknown, portfolio: string | null, listing: string | null, binding: string): asserts value is ListingReviewState {
  const parsed = stateSchema.safeParse(value); if (!parsed.success) throw new Error("LISTING_REVIEW_RESPONSE_INVALID"); const state = parsed.data;
  if (state.session_binding !== binding || (portfolio !== null && state.selected_portfolio_id !== portfolio) || state.selected_listing_id !== listing || (listing === null ? state.selected !== null : state.selected?.identity.listing_id !== listing)) throw new Error("LISTING_REVIEW_RESPONSE_INVALID");
  if (new Set(state.rows.map(row => row.identity.listing_id)).size !== state.rows.length || new Set(state.sources.map(source => source.id)).size !== state.sources.length || state.sources.some(source => source.portfolio_id !== state.selected_portfolio_id || source.known_at > state.checked_at)) throw new Error("LISTING_REVIEW_RESPONSE_INVALID");
  for (const item of [...state.rows, ...(state.selected ? [state.selected] : [])]) {
    const doc = item.current?.document;
    if (doc && (doc.portfolio_id !== state.selected_portfolio_id || doc.listing_id !== item.identity.listing_id || doc.revision > item.review_revision || doc.known_at > state.checked_at)) throw new Error("LISTING_REVIEW_RESPONSE_INVALID");
  }
  if (state.history.some(item => item.document.portfolio_id !== state.selected_portfolio_id || item.document.listing_id !== listing || item.document.known_at > state.checked_at)) throw new Error("LISTING_REVIEW_RESPONSE_INVALID");
}
export function prepareListingReviewAttempt(state: ListingReviewState, draft: ListingReviewDraft, binding: string, key: string): ListingReviewPending {
  if (state.read_only || !state.selected_portfolio_id || !state.selected_listing_id || !state.selected) throw new Error("LISTING_REVIEW_WRITE_LOCKED");
  const nullable = (value: string) => value === "" ? null : value;
  const parsed = publishListingReviewSchema.safeParse({ portfolio_id: state.selected_portfolio_id, listing_id: state.selected_listing_id, expected_review_revision: state.selected.review_revision, expected_identity_hash: state.selected.identity_hash, source_id: draft.sourceId, source_hash: draft.sourceHash,
    facts: { instrument_kind: draft.instrumentKind, lifecycle_status: draft.lifecycleStatus, quantity_step: nullable(draft.quantityStep), price_step: nullable(draft.priceStep), source_effective_date: nullable(draft.effectiveDate), fund_identifier: nullable(draft.fundId), share_class_identifier: nullable(draft.shareClassId), risk_classification: { index_id: nullable(draft.indexId), region: nullable(draft.region), sector: nullable(draft.sector) }, product_structure: { leverage: draft.leverage, direction: draft.direction } }, review_until: draft.reviewUntil, reason: draft.reason, acknowledgement: true, idempotency_key: key });
  if (!parsed.success || parsed.data.review_until <= state.checked_at || !reviewHash.safeParse(binding).success) throw new Error("LISTING_REVIEW_INVALID_COMMAND");
  const source = state.sources.find(source => source.id === draft.sourceId); if (source && source.content_hash !== draft.sourceHash) throw new Error("LISTING_REVIEW_SOURCE_CONFLICT");
  return { portfolio: state.selected_portfolio_id, listing: state.selected_listing_id, binding, body: JSON.stringify({ action: "publish", command: parsed.data }), command: parsed.data, identity: structuredClone(state.selected.identity), sourceKnownAt: source?.known_at ?? null };
}
const canonical = (value: unknown): string => Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : value !== null && typeof value === "object" ? `{${Object.entries(value).sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}` : JSON.stringify(value);
async function digest(value: unknown) { return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(canonical(value)))), byte => byte.toString(16).padStart(2, "0")).join(""); }
const receiptSchema = z.object({ id: reviewId, portfolio_id: reviewId, listing_id: reviewId, revision: natural.refine(n => n > 0), content_hash: reviewHash, identity_hash: reviewHash, source_id: reviewId, source_hash: reviewHash, known_at: reviewInstant, review_until: reviewInstant, review_basis: z.literal("human_reviewed_not_provider_verified"), audit_id: reviewId, session_binding: reviewHash, document: documentSchema }).strict();
export async function assertListingReviewReceipt(value: unknown, pending: ListingReviewPending) {
  const parsed = receiptSchema.safeParse(value); if (!parsed.success) throw new Error("LISTING_REVIEW_RESPONSE_INVALID");
  const result = parsed.data, command = pending.command, doc: ListingReviewDocument = result.document;
  const expected: ListingReviewDocument = { schema_version: "listing-review-v1", id: result.id, portfolio_id: command.portfolio_id, listing_id: command.listing_id, revision: command.expected_review_revision + 1, source_id: command.source_id, source_hash: command.source_hash, source_known_at: pending.sourceKnownAt ?? doc.source_known_at, identity_snapshot: pending.identity, identity_hash: command.expected_identity_hash, known_at: result.known_at, created_by: doc.created_by, review_until: command.review_until, reason: command.reason, review_basis: "human_reviewed_not_provider_verified", facts: command.facts };
  if (result.session_binding !== pending.binding || result.portfolio_id !== command.portfolio_id || result.listing_id !== command.listing_id || result.revision !== expected.revision || result.identity_hash !== command.expected_identity_hash || result.source_id !== command.source_id || result.source_hash !== command.source_hash || result.review_until !== command.review_until || doc.source_known_at > doc.known_at || doc.known_at >= doc.review_until || canonical(doc) !== canonical(expected) || await digest(doc) !== result.content_hash || await digest(pending.identity) !== command.expected_identity_hash) throw new Error("LISTING_REVIEW_RESPONSE_INVALID");
  return result;
}
